name: Feature Request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Suggest **new features** for MudBlazor. For questions, use [Discussions](https://github.com/MudBlazor/MudBlazor/discussions) or [Discord](https://discord.gg/mudblazor).
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe your idea
      description: Explain the problem this feature would solve and how it should work.
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Alternatives and examples
      description: Other solutions you tried, or links/screenshots of similar features.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow the [Code of Conduct](https://github.com/MudBlazor/MudBlazor/blob/dev/CODE_OF_CONDUCT.md)
          required: true
