name: Feature Request
description: Suggest a new feature or improvement
labels: [triage, enhancement]
body:
  - type: markdown
    attributes:
      value: |
        This template is for **suggesting new features** in MudBlazor.
        If you have a question, please use [GitHub Discussions](https://github.com/MudBlazor/MudBlazor/discussions) or [Discord](https://discord.gg/mudblazor).
  - type: dropdown
    id: enhancement-type
    attributes:
      label: Feature request type
      options:
        - Enhance component
        - New component
        - Performance improvement
        - Other
    validations:
      required: true
  - type: input
    id: component-name
    attributes:
      label: Component name (if applicable)
      placeholder: MudComponent
  - type: textarea
    id: related-problem
    attributes:
      label: What problem does this solve?
      description: Explain the problem or limitation this feature would solve.
  - type: textarea
    id: expected-behavior
    attributes:
      label: Describe your idea
      description: Explain how the new feature should work.
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Examples or references
      description: To maximize your chances of getting this implemented, share links, screenshots, or docs you found online with similar features.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you tried
      description: Describe other solutions or work-arounds you tried or considered.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting, you agree to follow our [Code of Conduct](https://github.com/MudBlazor/MudBlazor/blob/dev/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
