on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            let labels = [];
        
            if (body.includes("### Feature request type\n\nNew component")) {
              labels.push("new component");
              console.log("Feature request type: new component.");
              
            } else if (body.includes("### Feature request type\n\nPerformance improvement")) {
              labels.push("performance");
              console.log("Feature request type: Performance improvement.");
              
            } else if (body.includes("### Bug type\n\nDocs (mudblazor.com)")) {
              labels.push("docs");
              console.log("Bug type: docs.");
            }
            
            if(labels.length != 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              })
            }