on:
  pull_request_target:
    types: [opened]

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body;
            const title = pr.title;
            let labels = [];
            const isChecked = /-\s*\[\s*[x|X]\s*\]\s*/;
            
            // Check type of change checkboxes
            if(RegExp(isChecked.source + "Bug fix").test(body)) {
              labels.push("bug");
              console.log("PR type: bug fix.");
            }
            
            if(RegExp(isChecked.source + "New feature").test(body)) {
              labels.push("enhancement");
              console.log("PR type: enhancement.");
            }

            if(RegExp(isChecked.source + "Other").test(body)) {
              console.log("PR type: other.");
            }
            
            // Check title prefixes
            if(/^build:/i.test(title)) {
              labels.push("build");
              console.log("PR title indicates: build.");
            }
            
            if(/^docs:/i.test(title)) {
              labels.push("docs");
              console.log("PR title indicates: docs.");
            }
            
            // Check for keywords in title
            if(/tests/i.test(title)) {
              labels.push("tests");
              console.log("PR title indicates: tests.");
            }
            
            if(/refactor/i.test(title)) {
              labels.push("refactor");
              console.log("PR title indicates: refactor.");
            }
            
            if(labels.length != 0) {
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: labels
              })
            }
