name: Triage Backlog

on:
  schedule:
    - cron: '0 6 * * *' # This will take until 2026 to get through the backlog, which gives us many chances to iterate on the triage process.
  
  workflow_dispatch:
    inputs:
      backlog-size:
        description: 'Number of issues to process'
        required: false
        default: '1'
        type: string
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: false
        type: boolean

jobs:
  backlog-triage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: npm install node-fetch@2 @actions/core @actions/github
    
    - name: Run AI backlog triage script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AUTOTRIAGE_ENABLED: ${{ vars.AUTOTRIAGE_ENABLED }}
        AUTOTRIAGE_VERBOSE: ${{ github.event.inputs.verbose }}
        AUTOTRIAGE_PROMPT: ${{ vars.AUTOTRIAGE_PROMPT }}
        AUTOTRIAGE_MODEL: ${{ vars.AUTOTRIAGE_MODEL }}
        AUTOTRIAGE_LABELS: ${{ vars.AUTOTRIAGE_LABELS }}
        BACKLOG_SIZE: ${{ github.event.inputs.backlog-size || '1' }} # Avoid overwhelming the API (https://ai.google.dev/gemini-api/docs/rate-limits).
      run: node ./.github/scripts/AutoTriageBacklog.js
